//
// Generated file, do not edit! Created by nedtool 5.1 from veins/modules/application/platooning/self_organization/ExtendedPlatooningBeacon.msg.
//

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#ifndef __EXTENDEDPLATOONINGBEACON_M_H
#define __EXTENDEDPLATOONINGBEACON_M_H

#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0501
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
#include "veins/modules/application/platooning/messages/PlatooningBeacon_m.h"
// }}

/**
 * Class generated from <tt>veins/modules/application/platooning/self_organization/ExtendedPlatooningBeacon.msg:24</tt> by nedtool.
 * <pre>
 * packet ExtendedPlatooningBeacon extends PlatooningBeacon
 * {
 *     int laneIndex = -1;
 * }
 * </pre>
 */
class ExtendedPlatooningBeacon : public ::PlatooningBeacon
{
  protected:
    int laneIndex;

  private:
    void copy(const ExtendedPlatooningBeacon& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const ExtendedPlatooningBeacon&);

  public:
    ExtendedPlatooningBeacon(const char *name=nullptr, short kind=0);
    ExtendedPlatooningBeacon(const ExtendedPlatooningBeacon& other);
    virtual ~ExtendedPlatooningBeacon();
    ExtendedPlatooningBeacon& operator=(const ExtendedPlatooningBeacon& other);
    virtual ExtendedPlatooningBeacon *dup() const override {return new ExtendedPlatooningBeacon(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getLaneIndex() const;
    virtual void setLaneIndex(int laneIndex);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const ExtendedPlatooningBeacon& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, ExtendedPlatooningBeacon& obj) {obj.parsimUnpack(b);}


#endif // ifndef __EXTENDEDPLATOONINGBEACON_M_H

